import type { Database } from 'better-sqlite3';

import { assertReleaseSchemaComponentTransaction, assertReleaseSchemaObjectsAbsent } from './release-schema-component-state.js';

export const SESSION_ACTORS_COMPONENT_ID = 'r3.actor-provenance-v2';
export const SESSION_ACTORS_DDL: readonly string[] = Object.freeze([
  "CREATE TABLE session_actors_v2 (session_id TEXT NOT NULL CHECK (typeof(session_id)='text' AND length(session_id) BETWEEN 1 AND 256), actor_id TEXT NOT NULL CHECK (typeof(actor_id)='text' AND length(actor_id)=68 AND substr(actor_id,1,4)='act_' AND substr(actor_id,5) NOT GLOB '*[^0-9a-f]*'), launch_link_sha256 TEXT NOT NULL CHECK (typeof(launch_link_sha256)='text' AND length(launch_link_sha256)=64 AND launch_link_sha256 NOT GLOB '*[^0-9a-f]*'), launch_evidence_sha256 TEXT NOT NULL CHECK (typeof(launch_evidence_sha256)='text' AND length(launch_evidence_sha256)=64 AND launch_evidence_sha256 NOT GLOB '*[^0-9a-f]*'), requested_role TEXT CHECK (requested_role IS NULL OR (typeof(requested_role)='text' AND length(requested_role) BETWEEN 1 AND 128)), requested_model TEXT CHECK (requested_model IS NULL OR (typeof(requested_model)='text' AND length(requested_model) BETWEEN 1 AND 128)), requested_reasoning_effort TEXT CHECK (requested_reasoning_effort IS NULL OR (typeof(requested_reasoning_effort)='text' AND length(requested_reasoning_effort) BETWEEN 1 AND 32)), observed_role TEXT CHECK (observed_role IS NULL OR (typeof(observed_role)='text' AND length(observed_role) BETWEEN 1 AND 128)), evidence_status TEXT NOT NULL CHECK (typeof(evidence_status)='text' AND evidence_status IN ('complete','partial','unavailable','mismatch')), evidence_code TEXT NOT NULL CHECK (typeof(evidence_code)='text' AND evidence_code IN ('complete','requested_invalid','observed_role_missing','role_mismatch','model_missing','model_mismatch','turn_evidence_conflict')), role_mismatch INTEGER NOT NULL CHECK (typeof(role_mismatch)='integer' AND role_mismatch IN (0,1)), model_mismatch INTEGER NOT NULL CHECK (typeof(model_mismatch)='integer' AND model_mismatch IN (0,1)), sort_order INTEGER NOT NULL CHECK (typeof(sort_order)='integer' AND sort_order >= 0 AND sort_order < 256), PRIMARY KEY (session_id, actor_id), UNIQUE (session_id, launch_link_sha256), FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE)",
  "CREATE TABLE session_actor_model_observations_v2 (session_id TEXT NOT NULL CHECK (typeof(session_id)='text' AND length(session_id) BETWEEN 1 AND 256), actor_id TEXT NOT NULL CHECK (typeof(actor_id)='text' AND length(actor_id)=68 AND substr(actor_id,1,4)='act_' AND substr(actor_id,5) NOT GLOB '*[^0-9a-f]*'), observation_ordinal INTEGER NOT NULL CHECK (typeof(observation_ordinal)='integer' AND observation_ordinal >= 0 AND observation_ordinal < 256), source_record_ordinal INTEGER NOT NULL CHECK (typeof(source_record_ordinal)='integer' AND source_record_ordinal >= 0 AND source_record_ordinal <= 9007199254740991), turn_id_sha256 TEXT NOT NULL CHECK (typeof(turn_id_sha256)='text' AND length(turn_id_sha256)=64 AND turn_id_sha256 NOT GLOB '*[^0-9a-f]*'), model TEXT NOT NULL CHECK (typeof(model)='text' AND length(model) BETWEEN 1 AND 128), evidence_sha256 TEXT NOT NULL CHECK (typeof(evidence_sha256)='text' AND length(evidence_sha256)=64 AND evidence_sha256 NOT GLOB '*[^0-9a-f]*'), PRIMARY KEY (session_id, actor_id, observation_ordinal), FOREIGN KEY (session_id, actor_id) REFERENCES session_actors_v2(session_id, actor_id) ON DELETE CASCADE)",
  "CREATE TABLE session_actors_meta_v2 (session_id TEXT PRIMARY KEY CHECK (typeof(session_id)='text' AND length(session_id) BETWEEN 1 AND 256), source_revision_sha256 TEXT NOT NULL CHECK (typeof(source_revision_sha256)='text' AND length(source_revision_sha256)=64 AND source_revision_sha256 NOT GLOB '*[^0-9a-f]*'), parser_contract_sha256 TEXT NOT NULL CHECK (typeof(parser_contract_sha256)='text' AND length(parser_contract_sha256)=64 AND parser_contract_sha256 NOT GLOB '*[^0-9a-f]*'), cache_revision INTEGER NOT NULL CHECK (typeof(cache_revision)='integer' AND cache_revision >= 1 AND cache_revision <= 9007199254740991), actors_status TEXT NOT NULL CHECK (typeof(actors_status)='text' AND actors_status IN ('complete','partial','unavailable')), status_reason TEXT NOT NULL CHECK (typeof(status_reason)='text' AND status_reason IN ('complete','no_children','child_binding_absent','child_binding_invalid','child_lineage_invalid','evidence_cap_exceeded','source_drift','authorization_revoked','partial_actor_evidence')), actor_count INTEGER NOT NULL CHECK (typeof(actor_count)='integer' AND actor_count >= 0 AND actor_count <= 256), parsed_at_ms INTEGER NOT NULL CHECK (typeof(parsed_at_ms)='integer' AND parsed_at_ms >= 0 AND parsed_at_ms <= 9007199254740991), FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE)",
  "CREATE INDEX idx_session_actors_v2_order ON session_actors_v2(session_id, sort_order, actor_id)",
  "CREATE INDEX idx_session_actor_models_v2_order ON session_actor_model_observations_v2(session_id, actor_id, observation_ordinal)"
]);
export const SESSION_ACTORS_OBJECTS = Object.freeze(['session_actors_v2', 'session_actor_model_observations_v2', 'session_actors_meta_v2', 'idx_session_actors_v2_order', 'idx_session_actor_models_v2_order']);

/** Pure absent-state component; exact-target governed replay belongs to the composite owner. */
export function applySessionActorsV2Schema(db: Database): void {
  assertReleaseSchemaComponentTransaction(db);
  assertReleaseSchemaObjectsAbsent(db, SESSION_ACTORS_COMPONENT_ID, SESSION_ACTORS_OBJECTS);
  for (const ddl of SESSION_ACTORS_DDL) db.exec(ddl);
}
