/**
 * In-memory WebAuthn challenge store (B-PK-2, hardened by B-1407).
 *
 * Holds outstanding ceremony challenges between the options call and the
 * verify call. Keyed by the challenge string itself (base64url, generated by
 * @simplewebauthn — 32 random bytes, unguessable). Every entry is bound to a
 * PURPOSE and, where relevant, a user and an audience:
 *
 *   login         anonymous passkey sign-in (userId null)
 *   registration  a signed-in user enrolling a passkey (userId set)
 *   step_up       a signed-in user re-proving presence for `audience`
 *                 (userId + audience set; at most ONE pending per user —
 *                 a new step-up challenge replaces the previous one)
 *
 * consume() returns null on ANY mismatch (purpose, user, audience, expiry)
 * and always removes the entry, so a challenge issued for one ceremony can
 * never be replayed into another and a replayed assertion never verifies twice.
 *
 * Bounded: expired entries are swept on every store(), and each purpose has
 * its own cap so anonymous login traffic cannot starve the authenticated
 * ceremonies (and vice versa). A full purpose throws ChallengeStoreFullError,
 * which the service maps to 503.
 *
 * Single-process only (Map, no shared store) — adequate for the single PM2
 * fork this app runs as, mirroring the in-memory rate limiter.
 */

const DEFAULT_TTL_MS = 5 * 60_000; // 5 minutes

/** Per-purpose pending-challenge caps. */
export const DEFAULT_CHALLENGE_CAPS = Object.freeze({
  login: 1000,
  registration: 500,
  step_up: 500,
});

export const CHALLENGE_PURPOSES = Object.freeze(['login', 'registration', 'step_up']);

/** Thrown by store() when the purpose's cap is reached after the expiry sweep. */
export class ChallengeStoreFullError extends Error {
  constructor(purpose) {
    super('webauthn_challenge_store_full');
    this.purpose = purpose;
  }
}

const isUserId = (value) => Number.isSafeInteger(value) && value > 0;

/** Validates the binding shape per purpose; throws on programmer error. */
function assertBinding({ userId = null, purpose, audience = null }) {
  if (!CHALLENGE_PURPOSES.includes(purpose)) {
    throw new Error('webauthn_challenge_purpose_invalid');
  }
  if (purpose === 'login' ? userId !== null : !isUserId(userId)) {
    throw new Error('webauthn_challenge_user_invalid');
  }
  if (purpose === 'step_up' ? typeof audience !== 'string' || !audience : audience !== null) {
    throw new Error('webauthn_challenge_audience_invalid');
  }
}

/**
 * Factory — exported for unit tests (short TTLs, small caps, isolated state).
 * @param {{ ttlMs?: number, caps?: Partial<Record<'login'|'registration'|'step_up', number>> }} [options]
 */
export function createChallengeStore({ ttlMs, caps } = {}) {
  const ttl = ttlMs ?? DEFAULT_TTL_MS;
  const limits = { ...DEFAULT_CHALLENGE_CAPS, ...caps };
  /** @type {Map<string, { userId: number | null, purpose: string, audience: string | null, expiresAt: number }>} */
  const challenges = new Map();
  /** userId → its single pending step_up challenge. */
  const pendingStepUp = new Map();

  function remove(challenge, entry) {
    challenges.delete(challenge);
    if (entry.purpose === 'step_up' && pendingStepUp.get(entry.userId) === challenge) {
      pendingStepUp.delete(entry.userId);
    }
  }

  /** Drops expired entries and returns the live count for `purpose`. */
  function sweep(now, purpose) {
    let live = 0;
    for (const [key, entry] of challenges) {
      if (now > entry.expiresAt) {
        remove(key, entry);
      } else if (entry.purpose === purpose) {
        live += 1;
      }
    }
    return live;
  }

  return {
    /**
     * Registers a pending challenge bound to its ceremony.
     * @param {string} challenge base64url challenge from generate*Options
     * @param {{ userId?: number | null, purpose: 'login'|'registration'|'step_up',
     *           audience?: string | null }} binding
     * @throws {ChallengeStoreFullError} when the purpose's cap is reached
     */
    store(challenge, binding) {
      const { userId = null, purpose, audience = null } = binding ?? {};
      assertBinding({ userId, purpose, audience });
      const now = Date.now();
      if (purpose === 'step_up') {
        const previous = pendingStepUp.get(userId);
        if (previous !== undefined) {
          remove(previous, challenges.get(previous) ?? { purpose, userId });
        }
      }
      if (sweep(now, purpose) >= limits[purpose]) {
        throw new ChallengeStoreFullError(purpose);
      }
      challenges.set(challenge, { userId, purpose, audience, expiresAt: now + ttl });
      if (purpose === 'step_up') {
        pendingStepUp.set(userId, challenge);
      }
    },

    /**
     * Consumes a challenge (single use). Returns the binding only when the
     * entry exists, has not expired and matches `expected` exactly (purpose,
     * userId — null for login — and audience); null otherwise. The entry is
     * always removed, so a second consume of the same challenge fails.
     * @param {string} challenge
     * @param {{ purpose: string, userId?: number | null, audience?: string | null }} expected
     * @returns {{ userId: number | null, purpose: string, audience: string | null } | null}
     */
    consume(challenge, expected) {
      if (typeof challenge !== 'string' || challenge.length === 0) {
        return null;
      }
      const entry = challenges.get(challenge);
      if (!entry) {
        return null;
      }
      remove(challenge, entry);
      if (Date.now() > entry.expiresAt) {
        return null;
      }
      if (
        !expected ||
        entry.purpose !== expected.purpose ||
        entry.userId !== (expected.userId ?? null) ||
        entry.audience !== (expected.audience ?? null)
      ) {
        return null;
      }
      return { userId: entry.userId, purpose: entry.purpose, audience: entry.audience };
    },

    /** Number of pending (possibly expired, not yet swept) challenges. */
    get size() {
      return challenges.size;
    },
  };
}

/** Process-wide singleton used by the WebAuthn routes/service. */
export const webauthnChallengeStore = createChallengeStore();
